version: "2.4"
services:
#  messenger-api:
#    image: ${REGISTRY_URL}/messenger-api:${IMAGE_TAG:-latest}
#    build:
#      context: ../../
#      dockerfile: Messenger.Api/Dockerfile
#      target: final
  postgres:
    image: postgres:alpine
    ports:
      - "6666:5432"
    environment:
      POSTGRES_PASSWORD: fd2ee12swq
      POSTGRES_DB: dreamspb
  
  redis-data:
    image: redis:alpine
    ports:
      - "127.0.0.1:6380:6379"
  
  seq:
    image: datalust/seq
    ports:
      - "5100:80"
    environment:
      ACCEPT_EULA: Y

volumes:
  minio:
  
#  rabbitmq:
#    image: rabbitmq:3-management-alpine
#    ports:
#      - "15672:15672"

