version: "2.4"
services:
  repet-api:
    image: ${REGISTRY_URL}messenger-api:${IMAGE_TAG:-latest}
    build:
      context: ../../
      dockerfile: Messenger.Api/Dockerfile
      target: final
      args:
        - CI_JOB_TOKEN=${CI_JOB_TOKEN}