version: "2.4"
services:
  frontend:
    image: messenger-frontend
    build:
      context: ../../../../frontend
      dockerfile: Dockerfile
    ports:
      - "6390:80"

  messenger-api:
    image: messenger-api
    build:
      context: ../../
      dockerfile: Messenger.Api/Dockerfile
      target: final
    environment:
      "ConnectionStrings:DataConnectionString": "Host=postgres;Port=5432;Database=Messenger;Username=postgres;Password=fd2ee12swq" 
      "ConnectionStrings:RedisConnectionString": "redis-data:6379"
    networks: 
      - default

  postgres:
    image: postgres:alpine
    ports:
      - "6666:5432"
    environment:
      POSTGRES_PASSWORD: fd2ee12swq
      POSTGRES_DB: dreamspb
    networks:
      - default
  
  redis-data:
    image: redis:alpine
    ports:
      - "127.0.0.1:6380:6379"
    networks:
      - default
  
  seq:
    image: datalust/seq
    ports:
      - "5100:80"
    environment:
      ACCEPT_EULA: Y
      
  minio:
    image: minio/minio:RELEASE.2023-01-12T02-06-16Z
    ports:
      - "9005:9000"
      - "9006:9006"
    volumes:
      - minio:/data
    environment:
      MINIO_ROOT_USER: minio
      MINIO_ROOT_PASSWORD: minio123
      MINIO_BROWSER: "on"
    command: server /data --console-address :9006

volumes:
  minio:

networks:
  default:
# Раскоментировать для нагрузочного теста
#  tank:
#    name: yandex-tank
#    external: true
