version: "2.4"
services:
  supportmq:
    container_name: supportmq
    tty: true
    hostname: supportmq
    ports:
      - "15672:15672"
      - "5672:5672"
    image: rabbitmq:3-management
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=admin