apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.serviceAccount.name | default (include "messenger-db.fullname" .) }}
data:
  POSTGRES_PASSWORD: {{ .Values.postgresql.password | b64enc }}
  POSTGRES_USER: {{ .Values.postgresql.user | b64enc }}