apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: backend
spec:
  entryPoints:
    - web
  routes:
    - match: PathPrefix(`{{ .Values.backend.path }}`)
      kind: Rule
      services:
        - name: {{ include "meesenger-backend.fullname" . }}
          port: 80