apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: {{ include "meesenger-backend.fullname" . }}-route
spec:
  entryPoints:
    - websecure
  routes:
    - match: PathPrefix(`{{ .Values.backend.path }}`) || Host(`messenger.admad.ru`) && PathPrefix(`{{ .Values.backend.path }}`)
      kind: Rule
      services:
        - name: {{ include "meesenger-backend.fullname" . }}
          port: 80
      middlewares:
        - name: {{ include "meesenger-backend.fullname" . }}-stripprefix
  tls:
    certResolver: letsencrypt