apiVersion: traefik.io/v1alpha1
kind: IngressRoute
metadata:
  name: frontend
spec:
  entryPoints:
    - web
    - websecure
  routes:
    - match: PathPrefix(`/`)
      kind: Rule
      services:
        - name: {{ include "meesenger-frontend.fullname" . }}
          port: 8080
      middlewares:
        - name: redirect-https